package:
  name: pdal-parallelizer
  version: 1.10.15

source:
  fn: pdal-parallelizer-1.10.15.tar.gz
  url: https://files.pythonhosted.org/packages/7c/9b/81a92c9e0d149c1f04f71691b702c05e571b2a229f52a239d273533f2367/pdal-parallelizer-1.10.15.tar.gz
  md5: 26ab77f8d5d04c88456aa8d9535a8300

build:
  number: 0

requirements:
  build:
    - python
  run:
    - python
    - numpy
    - click
    - pdal
    - python-pdal
    - dask
    - distributed
    - twine
    - pandas
    - matplotlib
    - pyproj

test:
  imports:
    - pdal-parallelizer

about:
  home: https://github.com/meldig/pdal-parallelizer
  license: BSD-3-Clause
  summary: "A simple commandline app to parallelize your pdal pipelines on point clouds"
