package:
  name: pdal-parallelizer
  version: 1.10.16

source:
  fn: pdal-parallelizer-1.10.16.tar.gz
  url: https://files.pythonhosted.org/packages/e6/c0/de5e2a66d258cd2aaea78b2e1f1a60c16867c3e4b6f6fd11f51fded79f85/pdal-parallelizer-1.10.16.tar.gz
  md5: c34b1c8b42c577237b1d0656e43a2a8c

build:
  number: 0

requirements:
  build:
    - python
  run:
    - python
    - click
    - pdal
    - python-pdal
    - dask
    - distributed
    - twine
    - pandas
    - pyproj
    - matplotlib

test:
  imports:
    - pdal-parallelizer

about:
  home: https://github.com/meldig/pdal-parallelizer
  license: BSD-3-Clause
  summary: "A simple commandline app to parallelize your pdal pipelines on point clouds"